### ISSUE TITLE
TypeError: path.existsSync is not a function

### ISSUE THREAD

**Issue by stevermeister** [filearts/plunker#109]
getting this error for 

> node server.js

command

**Comment by ggoodman** [comment]
Hi @stevermeister, I'm afraid I need more context here.

The contents of this repo are deprecated and the README refers to multiple independent servers needed to run Plunker.

**Comment by stevermeister** [comment]
more context:

```
/Users/stevermeister/workspace/plunker/node_modules/nconf/lib/nconf/stores/file.js:116
  if (!path.existsSync(self.file)) {
            ^

TypeError: path.existsSync is not a function
    at File.loadSync (/Users/stevermeister/workspace/plunker/node_modules/nconf/lib/nconf/stores/file.js:116:13)
    at Provider.add (/Users/stevermeister/workspace/plunker/node_modules/nconf/lib/nconf/provider.js:109:23)
    at Provider.(anonymous function) [as file] (/Users/stevermeister/workspace/plunker/node_modules/nconf/lib/nconf/provider.js:34:17)
    at Object.<anonymous> (/Users/stevermeister/workspace/plunker/server.js:9:4)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Function.Module.runMain (module.js:457:10)
    at startup (node.js:138:18)
```

> The contents of this repo are deprecated

oh, I thought you forwarded me to this repo in gitter, not just for readme.

**Comment by henfee** [comment]
path.existsSync change to fs.existsSync

**Comment by dkent600** [comment]
For me, both `path.existsSync` and `fs.existsSync` are undefined.

Using webpack.  nconf v0.10.0

**Comment by dkent600** [comment]
I'm using v0.10.0 in a web app using webpack and I get

"TypeError: existsSync is not a function"
